job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-mena
    APP_HOSTPATH: mena
    WP_DB_NAME_PREFIX: mena_wordpress
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-mena
    NEWRELIC_APPNAME: P4 Mena Development
    WP_DB_NAME: mena_wordpress_develop
    WP_STATELESS_BUCKET: planet4-mena-stateless-develop
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: release.k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: mena
    HELM_RELEASE: planet4-mena-release
    NEWRELIC_APPNAME: P4 Mena Release
    WP_DB_NAME: mena_wordpress_release
    WP_STATELESS_BUCKET: planet4-mena-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: www.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: mena
    HELM_RELEASE: planet4-mena-master
    NEWRELIC_APPNAME: P4 Mena Production
    WP_DB_NAME: mena_wordpress_master
    WP_STATELESS_BUCKET: planet4-mena-stateless
